spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  storage:
    s3:
      bucket: ${S3_BUCKET}
      region: ${S3_REGION}

logging:
  level:
    root: INFO
    nbc.profile: INFO
    org.hibernate.SQL: WARN
