#!/usr/bin/env bash
# AWS Auto Scaling Group Launch Template 용 user-data.
# 대상: Amazon Linux 2023 + IAM Role (profile-app-s3-policy + SSM read).
# 멱등: 재실행/재부팅 안전.
# 로그: cloud-init 이 stdout/stderr 를 /var/log/cloud-init-output.log 로 캡처.
# 결정 근거: docs/adr/0014-prod-rds-mysql-migration.md (.env 키 명세)

set -euo pipefail

# ---------- 공통 helper ----------
log()  { echo "[user-data] $(date -u '+%FT%TZ') $*"; }
fail() { log "FAIL: $*"; exit 1; }
trap 'log "ERR at line $LINENO (exit=$?)"; exit 1' ERR

REGION="ap-northeast-2"
SSM_PATH="/profile/prod"
ENV_FILE="/home/ec2-user/.env"
CONTAINER="nbc-profile"
IMAGE="rlawnstj90/nbc-profile:latest"

log "==== START user-data ===="
log "region=$REGION  ssm-path=$SSM_PATH  image=$IMAGE"

# ===========================================
# [1/5] Docker 설치 + 기동
# ===========================================
log "[1/5] Docker 설치 + 기동"

if command -v docker >/dev/null 2>&1; then
  log "  docker 이미 설치됨: $(docker --version)"
else
  log "  dnf install -y docker"
  dnf install -y docker || fail "[1/5] docker 설치 실패"
fi

systemctl enable --now docker || fail "[1/5] docker 서비스 기동 실패"

# ec2-user 가 docker 그룹에 없으면 추가 (재로그인 필요하나 root 권한 명령은 즉시 가능)
if ! id -nG ec2-user | grep -qw docker; then
  usermod -aG docker ec2-user
  log "  ec2-user 를 docker 그룹에 추가"
fi

log "[1/5] OK — $(docker --version), service=$(systemctl is-active docker)"

# ===========================================
# [2/5] Parameter Store → /home/ec2-user/.env
# ===========================================
log "[2/5] SSM Parameter Store fetch (경로=$SSM_PATH)"

# AWS CLI 는 AL2023 기본 포함. IAM Role 자격으로 인증 (키 불필요).
# get-parameters-by-path 한 번 호출 = N개 파라미터 일괄 fetch.
# --query 로 Name<TAB>Value 형식 추출 → bash 파싱.
PARAMS=$(aws ssm get-parameters-by-path \
  --path "$SSM_PATH" \
  --recursive \
  --with-decryption \
  --region "$REGION" \
  --query 'Parameters[].[Name,Value]' \
  --output text 2>&1) || fail "[2/5] SSM fetch 실패 — IAM Role 권한(ssm:GetParametersByPath + kms:Decrypt) 확인. 원문: $PARAMS"

if [ -z "$PARAMS" ]; then
  fail "[2/5] SSM 결과 0건 — 경로 $SSM_PATH 아래 파라미터 존재 여부 + Region 확인"
fi

# SSM 경로 → .env 변수명 매핑
declare -A MAP=(
  ["$SSM_PATH/db/host"]="DB_HOST"
  ["$SSM_PATH/db/port"]="DB_PORT"
  ["$SSM_PATH/db/name"]="DB_NAME"
  ["$SSM_PATH/db/username"]="DB_USERNAME"
  ["$SSM_PATH/db/password"]="DB_PASSWORD"
  ["$SSM_PATH/s3/bucket-name"]="S3_BUCKET"
  ["$SSM_PATH/s3/region"]="S3_REGION"
  ["$SSM_PATH/app/team-name"]="TEAM_NAME"
)

# 임시 파일에 빌드 → 마지막에 atomic mv (부분 실패 시 .env 손상 방지)
TMP_ENV="$(mktemp)"
{
  echo "# Generated by user-data $(date -u '+%FT%TZ') — SSM path $SSM_PATH"
  echo "# S3_ACCESS_KEY / S3_SECRET_KEY 는 IAM Role 위임 (ADR-0004 fallback)"
  echo "SPRING_PROFILES_ACTIVE=prod"
} > "$TMP_ENV"

# Docker --env-file 포맷: KEY=VALUE 한 줄, 값 quote 안 함 (literal 으로 전달됨).
# 값에 newline 이 있으면 깨짐 — SSM SecureString 은 일반적으로 single-line.
while IFS=$'\t' read -r NAME VALUE; do
  ENV_VAR="${MAP[$NAME]:-}"
  if [ -n "$ENV_VAR" ]; then
    echo "${ENV_VAR}=${VALUE}" >> "$TMP_ENV"
    log "  mapped: $NAME → $ENV_VAR"
  else
    log "  WARN: 매핑 없는 파라미터 $NAME (스킵)"
  fi
done <<< "$PARAMS"

# 필수 키 모두 수신했는지 검증
REQUIRED=(DB_HOST DB_PORT DB_NAME DB_USERNAME DB_PASSWORD S3_BUCKET S3_REGION)
MISSING=()
for K in "${REQUIRED[@]}"; do
  grep -q "^${K}=" "$TMP_ENV" || MISSING+=("$K")
done
if [ "${#MISSING[@]}" -gt 0 ]; then
  rm -f "$TMP_ENV"
  fail "[2/5] 필수 env 누락: ${MISSING[*]} — Parameter Store 에 해당 키 등록 필요"
fi

# atomic mv + 권한
install -m 600 -o ec2-user -g ec2-user "$TMP_ENV" "$ENV_FILE"
rm -f "$TMP_ENV"

# 키 목록만 로깅 (값은 절대 로그에 남기지 않음)
log "[2/5] OK — .env 키: $(cut -d= -f1 "$ENV_FILE" | grep -v '^#' | grep -v '^$' | tr '\n' ' ')"

# ===========================================
# [3/5] Docker 이미지 pull
# ===========================================
log "[3/5] docker pull $IMAGE"
docker pull "$IMAGE" || fail "[3/5] pull 실패 — repo public 여부 + outbound 네트워크 확인"
log "[3/5] OK — $(docker image inspect "$IMAGE" --format '{{.Id}} ({{.Size}} bytes)' | head -1)"

# ===========================================
# [4/5] 컨테이너 실행 (기존 동명 컨테이너 제거)
# ===========================================
log "[4/5] 컨테이너 기동 (name=$CONTAINER)"

if docker ps -aq -f "name=^${CONTAINER}$" | grep -q .; then
  log "  기존 컨테이너 발견 — stop/rm"
  docker stop "$CONTAINER" >/dev/null 2>&1 || true
  docker rm   "$CONTAINER" >/dev/null 2>&1 || true
fi

docker run -d \
  --name "$CONTAINER" \
  --env-file "$ENV_FILE" \
  -p 8080:8080 \
  --restart unless-stopped \
  "$IMAGE" \
  || fail "[4/5] docker run 실패"

log "[4/5] OK — container id=$(docker ps -q -f name=$CONTAINER)"

# ===========================================
# [5/5] 검증 (health gate 최대 60s)
# ===========================================
log "[5/5] health 체크 (최대 60s, 2s × 30 polling)"

for i in $(seq 1 30); do
  if HEALTH=$(curl -fsS http://localhost:8080/actuator/health 2>/dev/null) && \
     echo "$HEALTH" | grep -q '"UP"'; then
    log "[5/5] OK (i=$i) — health: $HEALTH"
    docker ps --filter "name=$CONTAINER" --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}'
    log "==== user-data 완료 ===="
    exit 0
  fi
  sleep 2
done

log "[5/5] health timeout — 컨테이너 로그 마지막 100줄:"
docker logs --tail 100 "$CONTAINER" || true
docker ps --filter "name=$CONTAINER" --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'
fail "[5/5] /actuator/health UP 응답 부재 — 위 로그로 부팅 실패 원인 추적"
